name 'ghoneycutt-nrpe'
version '1.0.0'
source 'git://github.com/ghoneycutt/puppet-module-nrpe.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage NRPE'
description 'Manage NRPE - Nagios Remote Plugin Executor'
project_page 'https://github.com/ghoneycutt/puppet-module-nrpe'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
